### ISSUE TITLE
消息解码处理BUG,导致收不到消息.

### ISSUE THREAD

**Issue by tiansin** [juggleim/im-server#3]
这里直接err了,我看其它地方的`jg:text`处理都是正常的,只有这里的不一样用的map.
我看了下这个文件的git历史提交,上一版本的代码则能正常运行.
```
		txtMsg := &struct {
			Content string `json:"content"`
		}{}
		err = tools.JsonUnMarshal(upMsg.MsgContent, txtMsg)
```

```
			txtMsg := &commonservices.TextMsg{}
			err := tools.JsonUnMarshal(msg.MsgContent, txtMsg)
```

https://github.com/juggleim/im-server/blob/cbcb71b0d77629c5da484329b988b82d2740e94d/services/sensitivemanager/interceptor/adapters/local/local.go#L20

**Comment by ruziyi** [comment]
upMsg.MsgContent是什么内容呢？

**Comment by tiansin** [comment]
> upMsg.MsgContent是什么内容呢？

上面两段代码是正常的解码,只有`local.go`里边这个有问题

**Comment by tiansin** [comment]
https://github.com/juggleim/im-server/commit/118fa9d1e6b725662270d0cdb074276f346731f3#diff-abe590052f89542e8277d7b78ee99df8f94736a538a0624e97f2021b47979f22

**Comment by ruziyi** [comment]
因为msgContent可能还包含业务定义的未知其他字段， 所以定义成map。

**Comment by yuwnloyblog** [comment]
确实有问题，已经修复了，感谢
